# Generated by Django 6.0.2 on 2026-02-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_booking_travel_date_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image_url',
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(default='', upload_to='destinations/'),
            preserve_default=False,
        ),
    ]
